server.servlet.context-path: '/API/v1/finPick'
server:
  port: ${PORT:9997}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${:}
          username: ${REPO_USER:git_finPick}
          password: ${REPO_PASS:git_finPick_pass}
  security:
    user:
      name: ${SERVER_USER:git_finPick}
      password: ${SERVER_PASS:git_finPick_pass}